# -*- coding: utf-8 -*-
"""Script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qBxsm8OmTMH0vZsNErMzwWgMUR0AMY3D
"""

from google.colab import drive
drive.mount('/content/drive')

import os

#os.chdir('drive/My Drive')
print(os.getcwd())
os.chdir('project')
print(os.getcwd())

import numpy as np
import pandas as pd
import csv
from sklearn.tree import DecisionTreeClassifier

data=pd.read_csv("train.csv").as_matrix()
clf=DecisionTreeClassifier()

xtrain=data[0:42000,1:]
trainlabel=data[0:42000,0]
xzzx
clf.fit(xtrain,trainlabel)
data=pd.read_csv("test.csv").as_matrix()
xtest=data[0:28000,0:]
with open("new.csv", 'w') as f:
    f.write('ImageId,Label\n')
    for i in range(0,28000):
        x = clf.predict([xtest[i]])
        print(x[0])
        if i<27999:
          f.write(str(i+1)+','+str(x[0])+'\n')
        else:
          f.write(str(i+1)+','+str(x[0]))
    f.close()